language: cpp
services:
    - docker
git:
    depth: false
dist: trusty
sudo: required
matrix:
    include:
        - env: TARGET_OS=cross.win64
script:
    - docker pull veyon/travis.${TRAVIS_OS_NAME}.${TARGET_OS}:4.1 || docker build -t veyon/travis.${TRAVIS_OS_NAME}.${TARGET_OS} ${TRAVIS_BUILD_DIR}/.travis/${TRAVIS_OS_NAME}.${TARGET_OS}/
    - docker run -v ${TRAVIS_BUILD_DIR}:/veyon:rw veyon/travis.${TRAVIS_OS_NAME}.${TARGET_OS} /bin/sh /veyon/.travis/${TRAVIS_OS_NAME}.${TARGET_OS}/script.sh
deploy:
    provider: releases
    api_key: baed2074976f92649e7740415884913f930d31f5
    repo: cnyehua1/veyon
    skip_cleanup: true
    file_glob: true
    file: "veyon*"
    on:
        tags: true
        all_branches: true
